// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton/test/presentation/pages/movie_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:ditonton/presentation/bloc/movie_detail_bloc.dart' as _i2;
import 'package:ditonton/presentation/bloc/movie_detail_recommendations_bloc.dart'
    as _i4;
import 'package:ditonton/presentation/bloc/movie_detail_watchlist_bloc.dart'
    as _i5;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieDetailState_0 extends _i1.Fake implements _i2.MovieDetailState {
}

class _FakeStreamSubscription_1<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

class _FakeMovieDetailRecommendationsState_2 extends _i1.Fake
    implements _i4.MovieDetailRecommendationsState {}

class _FakeMovieDetailWatchlistState_3 extends _i1.Fake
    implements _i5.MovieDetailWatchlistState {}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i2.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieDetailState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMovieDetailState_0()) as _i2.MovieDetailState);
  @override
  _i3.Stream<_i2.MovieDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.MovieDetailState>.empty())
          as _i3.Stream<_i2.MovieDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i2.MovieDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.MovieDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<
      _i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>> transformEvents(
          _i3.Stream<_i2.MovieDetailEvent>? events,
          _i6.TransitionFunction<_i2.MovieDetailEvent, _i2.MovieDetailState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>>.empty())
          as _i3.Stream<
              _i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>>);
  @override
  void emit(_i2.MovieDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i2.MovieDetailEvent>(
          _i6.EventHandler<E, _i2.MovieDetailState>? handler,
          {_i6.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i2.MovieDetailState> mapEventToState(
          _i2.MovieDetailEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.MovieDetailState>.empty())
          as _i3.Stream<_i2.MovieDetailState>);
  @override
  void onTransition(
          _i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<
      _i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>> transformTransitions(
          _i3.Stream<_i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>>?
              transitions) =>
      (super.noSuchMethod(
              Invocation.method(#transformTransitions, [transitions]),
              returnValue:
                  Stream<_i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>>.empty())
          as _i3.Stream<
              _i6.Transition<_i2.MovieDetailEvent, _i2.MovieDetailState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i2.MovieDetailState> listen(
          void Function(_i2.MovieDetailState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_1<_i2.MovieDetailState>())
          as _i3.StreamSubscription<_i2.MovieDetailState>);
  @override
  void onChange(_i6.Change<_i2.MovieDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieDetailRecommendationsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailRecommendationsBloc extends _i1.Mock
    implements _i4.MovieDetailRecommendationsBloc {
  MockMovieDetailRecommendationsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieDetailRecommendationsState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeMovieDetailRecommendationsState_2())
          as _i4.MovieDetailRecommendationsState);
  @override
  _i3.Stream<_i4.MovieDetailRecommendationsState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.MovieDetailRecommendationsState>.empty())
          as _i3.Stream<_i4.MovieDetailRecommendationsState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.MovieDetailRecommendationsEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.MovieDetailRecommendationsEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>>
      transformEvents(
              _i3.Stream<_i4.MovieDetailRecommendationsEvent>? events,
              _i6.TransitionFunction<_i4.MovieDetailRecommendationsEvent,
                      _i4.MovieDetailRecommendationsState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>>.empty())
              as _i3.Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>>);
  @override
  void emit(_i4.MovieDetailRecommendationsState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.MovieDetailRecommendationsEvent>(
          _i6.EventHandler<E, _i4.MovieDetailRecommendationsState>? handler,
          {_i6.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i4.MovieDetailRecommendationsState> mapEventToState(
          _i4.MovieDetailRecommendationsEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i4.MovieDetailRecommendationsState>.empty())
          as _i3.Stream<_i4.MovieDetailRecommendationsState>);
  @override
  void onTransition(
          _i6.Transition<_i4.MovieDetailRecommendationsEvent,
                  _i4.MovieDetailRecommendationsState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>> transformTransitions(
          _i3.Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>>?
              transitions) =>
      (super.noSuchMethod(Invocation.method(#transformTransitions, [transitions]),
              returnValue: Stream<_i6.Transition<_i4.MovieDetailRecommendationsEvent, _i4.MovieDetailRecommendationsState>>.empty())
          as _i3.Stream<
              _i6.Transition<_i4.MovieDetailRecommendationsEvent,
                  _i4.MovieDetailRecommendationsState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i4.MovieDetailRecommendationsState> listen(
          void Function(_i4.MovieDetailRecommendationsState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_1<
                  _i4.MovieDetailRecommendationsState>())
          as _i3.StreamSubscription<_i4.MovieDetailRecommendationsState>);
  @override
  void onChange(_i6.Change<_i4.MovieDetailRecommendationsState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieDetailWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailWatchlistBloc extends _i1.Mock
    implements _i5.MovieDetailWatchlistBloc {
  MockMovieDetailWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieDetailWatchlistState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeMovieDetailWatchlistState_3())
          as _i5.MovieDetailWatchlistState);
  @override
  _i3.Stream<_i5.MovieDetailWatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.MovieDetailWatchlistState>.empty())
          as _i3.Stream<_i5.MovieDetailWatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i5.MovieDetailWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i5.MovieDetailWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>
      transformEvents(
              _i3.Stream<_i5.MovieDetailWatchlistEvent>? events,
              _i6.TransitionFunction<_i5.MovieDetailWatchlistEvent,
                      _i5.MovieDetailWatchlistState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>.empty())
              as _i3.Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>);
  @override
  void emit(_i5.MovieDetailWatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i5.MovieDetailWatchlistEvent>(
          _i6.EventHandler<E, _i5.MovieDetailWatchlistState>? handler,
          {_i6.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i5.MovieDetailWatchlistState> mapEventToState(
          _i5.MovieDetailWatchlistEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i5.MovieDetailWatchlistState>.empty())
          as _i3.Stream<_i5.MovieDetailWatchlistState>);
  @override
  void onTransition(
          _i6.Transition<_i5.MovieDetailWatchlistEvent,
                  _i5.MovieDetailWatchlistState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>
      transformTransitions(
              _i3.Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>.empty())
              as _i3.Stream<
                  _i6.Transition<_i5.MovieDetailWatchlistEvent, _i5.MovieDetailWatchlistState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i5.MovieDetailWatchlistState> listen(
          void Function(_i5.MovieDetailWatchlistState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue:
                  _FakeStreamSubscription_1<_i5.MovieDetailWatchlistState>())
          as _i3.StreamSubscription<_i5.MovieDetailWatchlistState>);
  @override
  void onChange(_i6.Change<_i5.MovieDetailWatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
