name: core
description: Core module of Ditonton Application
version: 0.0.1
homepage:

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  equatable: ^2.0.3
  http: ^0.13.4
  dartz: ^0.10.0
  sqflite_common_ffi: ^2.1.0
  flutter_cache_manager: ^3.1.3
  cached_network_image: ^3.1.0
  path_provider: ^2.0.6  
  rxdart: ^0.27.2
  data_connection_checker:
     git:
       url: https://github.com/chornthorn/data_connection_checker.git
       ref: master
  movies:
    path: ../movies
  tv_shows:
    path: ../tv_shows


dev_dependencies:
  mockito: ^5.0.16
  mocktail: ^0.2.0
  build_runner: ^2.0.4
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/google_fonts/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
